#include <avr/io.h>
#include <avr/interrupt.h>
//#include <avr/delay.h>
#include "GPT.h"
#include "Std_Types.h"
#include "Bit_Math.h"
#include "Dio.h"

void GPT_Init() {
/**********************************************************
 * Timer 0 Initialization
 *********************************************************/
	#if GPT_TIM0_STATUS == GPT_ON
		#if GPT_TIM0_WAVEFROM_MODE == GPT_WAVEFORM_MODE_NORMAL
			RESET_BIT(TCCR0,WGM00);
			RESET_BIT(TCCR0,WGM01);
		#elif GPT_TIM0_WAVEFROM_MODE == GPT_WAVEFORM_MODE_CTC
			RESET_BIT(TCCR0,WGM00);
			SET_BIT(TCCR0,WGM01);
		#else
			#error "Invalid WAVEFORM MODE for Timer 0";
		#endif
		#if COMPARE_OUTPUT_MODE_TIM0 == COMPARE_OUTPUT_MODE_DISCONNECTED
			RESET_BIT(TCCR0,COM00);
			RESET_BIT(TCCR0,COM01);
		#elif COMPARE_OUTPUT_MODE_TIM0 == COMPARE_OUTPUT_MODE_TOG
			SET_BIT(TCCR0,COM00);
			SET_BIT(TCCR0,COM01);
		#elif COMPARE_OUTPUT_MODE_TIM0 == COMPARE_OUTPUT_MODE_CLR
			RESET_BIT(TCCR0,COM00);
			SET_BIT(TCCR0,COM01);
		#elif COMPARE_OUTPUT_MODE_TIM0 == COMPARE_OUTPUT_MODE_SET
			SET_BIT(TCCR0,COM00);
			RESET_BIT(TCCR0,COM01);
		#else
			#error "Invalid COMPARE_OUTPUT_MODE for Timer 0";
		#endif
		#if GPT_CLK_PRESCALER_TIM0 == GPT_CLK_OFF
			RESET_BIT(TCCR0,CS00);
			RESET_BIT(TCCR0,CS01);
			RESET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_1
			SET_BIT(TCCR0,CS00);
			RESET_BIT(TCCR0,CS01);
			RESET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_8
			RESET_BIT(TCCR0,CS00);
			SET_BIT(TCCR0,CS01);
			RESET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_64
			SET_BIT(TCCR0,CS00);
			SET_BIT(TCCR0,CS01);
			RESET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_256
			RESET_BIT(TCCR0,CS00);
			RESET_BIT(TCCR0,CS01);
			SET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_1024
			SET_BIT(TCCR0,CS00);
			RESET_BIT(TCCR0,CS01);
			SET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_EXT_FALLING
			RESET_BIT(TCCR0,CS00);
			SET_BIT(TCCR0,CS01);
			SET_BIT(TCCR0,CS02);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_EXT_RISING
			SET_BIT(TCCR0,CS00);
			SET_BIT(TCCR0,CS01);
			SET_BIT(TCCR0,CS02);
		#else
			#error "Invalid GPT_CLK for Timer 0";
		#endif
	#endif
/**********************************************************
 * Timer 1A Initialization
 *********************************************************/
	#if GPT_TIM1_STATUS == GPT_ON
		#if GPT_TIM1_WAVEFROM_MODE == GPT_WAVEFORM_MODE_NORMAL
			RESET_BIT(TCCR1A,WGM10);
			RESET_BIT(TCCR1A,WGM11);
		#elif GPT_TIM1_WAVEFROM_MODE == GPT_WAVEFORM_MODE_CTC
			RESET_BIT(TCCR1,WGM10);
			SET_BIT(TCCR1A,WGM11);
		#else
			#error "Invalid WAVEFORM MODE for Timer 0";
		#endif
		#if COMPARE_OUTPUT_MODE_TIM1 == COMPARE_OUTPUT_MODE_DISCONNECTED
			RESET_BIT(TCCR1A,COM1A0);
			RESET_BIT(TCCR1A,COM1A1);
		#elif COMPARE_OUTPUT_MODE_TIM1 == COMPARE_OUTPUT_MODE_TOG
			SET_BIT(TCCR1A,COM1A0);
			SET_BIT(TCCR1A,COM1A1);
		#elif COMPARE_OUTPUT_MODE_TIM1 == COMPARE_OUTPUT_MODE_CLR
			RESET_BIT(TCCR1A,COM1A0);
			SET_BIT(TCCR1A,COM1A1);
		#elif COMPARE_OUTPUT_MODE_TIM1 == COMPARE_OUTPUT_MODE_SET
			SET_BIT(TCCR1A,COM1A0);
			RESET_BIT(TCCR1A,COM1A1);
		#else
			#error "Invalid COMPARE_OUTPUT_MODE for Timer 0";
		#endif
		#if GPT_CLK_PRESCALER_TIM1 == GPT_CLK_OFF
			RESET_BIT(TCCR1B,CS10);
			RESET_BIT(TCCR1B,CS11);
			RESET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_1
			SET_BIT(TCCR1B,CS10);
			RESET_BIT(TCCR1B,CS11);
			RESET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_8
			RESET_BIT(TCCR1B,CS10);
			SET_BIT(TCCR1B,CS11);
			RESET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_64
			SET_BIT(TCCR1B,CS10);
			SET_BIT(TCCR1B,CS11);
			RESET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_256
			RESET_BIT(TCCR1B,CS10);
			RESET_BIT(TCCR1B,CS11);
			SET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_1024
			SET_BIT(TCCR1B,CS10);
			RESET_BIT(TCCR1B,CS11);
			SET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_EXT_FALLING
			RESET_BIT(TCCR1B,CS10);
			SET_BIT(TCCR1B,CS11);
			SET_BIT(TCCR1B,CS12);
		#elif GPT_CLK_PRESCALER_TIM1 == GPT_CLK_PRESCALER_EXT_RISING
			SET_BIT(TCCR1B,CS10);
			SET_BIT(TCCR1B,CS11);
			SET_BIT(TCCR1B,CS12);
		#else
			#error "Invalid GPT_CLK for Timer 0";
		#endif
	#endif
/**********************************************************
 * Timer 2 Initialization
 *********************************************************/
	#if GPT_TIM2_STATUS == GPT_ON
		#if GPT_TIM2_WAVEFROM_MODE == GPT_WAVEFORM_MODE_NORMAL
			RESET_BIT(TCCR2,WGM20);
			RESET_BIT(TCCR2,WGM21);
		#elif GPT_TIM2_WAVEFROM_MODE == GPT_WAVEFORM_MODE_CTC
			RESET_BIT(TCCR2,WGM20);
			SET_BIT(TCCR2,WGM21);
		#else
			#error "Invalid WAVEFORM MODE for Timer 0";
		#endif
		#if COMPARE_OUTPUT_MODE_TIM2 == COMPARE_OUTPUT_MODE_DISCONNECTED
			RESET_BIT(TCCR2,COM20);
			RESET_BIT(TCCR2,COM21);
		#elif COMPARE_OUTPUT_MODE_TIM2 == COMPARE_OUTPUT_MODE_TOG
			SET_BIT(TCCR2,COM20);
			SET_BIT(TCCR2,COM21);
		#elif COMPARE_OUTPUT_MODE_TIM2 == COMPARE_OUTPUT_MODE_CLR
			RESET_BIT(TCCR2,COM20);
			SET_BIT(TCCR2,COM21);
		#elif COMPARE_OUTPUT_MODE_TIM2 == COMPARE_OUTPUT_MODE_SET
			SET_BIT(TCCR2,COM20);
			RESET_BIT(TCCR2,COM21);
		#else
			#error "Invalid COMPARE_OUTPUT_MODE for Timer 0";
		#endif
		#if GPT_CLK_PRESCALER_TIM2 == GPT_CLK_OFF
			RESET_BIT(TCCR2,CS20);
			RESET_BIT(TCCR2,CS21);
			RESET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM2 == GPT_CLK_PRESCALER_1
			SET_BIT(TCCR2,CS20);
			RESET_BIT(TCCR2,CS21);
			RESET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM2 == GPT_CLK_PRESCALER_8
			RESET_BIT(TCCR2,CS20);
			SET_BIT(TCCR2,CS21);
			RESET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM2 == GPT_CLK_PRESCALER_64
			SET_BIT(TCCR2,CS20);
			SET_BIT(TCCR2,CS21);
			RESET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM0 == GPT_CLK_PRESCALER_256
			RESET_BIT(TCCR2,CS20);
			RESET_BIT(TCCR2,CS21);
			SET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM2 == GPT_CLK_PRESCALER_1024
			SET_BIT(TCCR2,CS20);
			RESET_BIT(TCCR2,CS21);
			SET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM2 == GPT_CLK_PRESCALER_EXT_FALLING
			RESET_BIT(TCCR2,CS20);
			SET_BIT(TCCR2,CS21);
			SET_BIT(TCCR2,CS22);
		#elif GPT_CLK_PRESCALER_TIM2 == GPT_CLK_PRESCALER_EXT_RISING
			SET_BIT(TCCR2,CS20);
			SET_BIT(TCCR2,CS21);
			SET_BIT(TCCR2,CS22);
		#else
			#error "Invalid GPT_CLK for Timer 0";
		#endif
	#endif
}

void GPT_EnableNotification(GPT_InterruptSourceType Channel)
{
	switch(Channel) {
	case GPT_TNT_SOURCE_TIM0_OV:
		SET_BIT(TIMSK,TOIE0);
		break;
	case GPT_TNT_SOURCE_TIM0_COMPARE:
		SET_BIT(TIMSK,OCIE0);
		break;
	case GPT_TNT_SOURCE_TIM1_OV:
		SET_BIT(TIMSK,TOIE1);
		break;
	case GPT_TNT_SOURCE_TIM1A_COMPARE:
		SET_BIT(TIMSK,OCIE1A);
		break;
	case GPT_TNT_SOURCE_TIM1B_COMPARE:
		SET_BIT(TIMSK,OCIE1B);
		break;
	case GPT_TNT_SOURCE_TIM2_OV:
		SET_BIT(TIMSK,TOIE2);
		break;
	case GPT_TNT_SOURCE_TIM2_COMPARE:
		SET_BIT(TIMSK,OCIE2);
		break;
	default:
		break;
	}
}

void GPT_DisableNotification(GPT_InterruptSourceType Channel)
{
	switch(Channel) {
	case GPT_TNT_SOURCE_TIM0_OV:
		RESET_BIT(TIMSK,TOIE0);
		break;
	case GPT_TNT_SOURCE_TIM0_COMPARE:
		RESET_BIT(TIMSK,OCIE0);
		break;
	case GPT_TNT_SOURCE_TIM1_OV:
		RESET_BIT(TIMSK,TOIE1);
		break;
	case GPT_TNT_SOURCE_TIM1A_COMPARE:
		RESET_BIT(TIMSK,OCIE1A);
		break;
	case GPT_TNT_SOURCE_TIM1B_COMPARE:
		RESET_BIT(TIMSK,OCIE1B);
		break;
	case GPT_TNT_SOURCE_TIM2_OV:
		RESET_BIT(TIMSK,TOIE2);
		break;
	case GPT_TNT_SOURCE_TIM2_COMPARE:
		RESET_BIT(TIMSK,OCIE2);
		break;
	default:
		break;
	}
}
