/*
 * GPT.h
 *
 *  Created on: Aug 22, 2023
 *      Author: Acer
 */

#ifndef GPT_H_
#define GPT_H_

#define GPT_OFF 0
#define GPT_ON 1

#define GPT_WAVEFORM_MODE_NORMAL 1
#define GPT_WAVEFORM_MODE_CTC 2

#define COMPARE_OUTPUT_MODE_DISCONNECTED 1
#define COMPARE_OUTPUT_MODE_TOG 2
#define COMPARE_OUTPUT_MODE_CLR 3
#define COMPARE_OUTPUT_MODE_SET 4

#define GPT_CLK_OFF 1
#define GPT_CLK_PRESCALER_1 2
#define GPT_CLK_PRESCALER_8 3
#define GPT_CLK_PRESCALER_32 4
#define GPT_CLK_PRESCALER_64 5
#define GPT_CLK_PRESCALER_128 6
#define GPT_CLK_PRESCALER_256 7
#define GPT_CLK_PRESCALER_1024 8
#define GPT_CLK_PRESCALER_EXT_FALLING 9
#define GPT_CLK_PRESCALER_EXT_RISING 10

#define GPT_TIM0_STATUS GPT_ON
#if GPT_TIM0_STATUS == GPT_ON
#define GPT_TIM0_WAVEFROM_MODE	 GPT_WAVEFORM_MODE_NORMAL
#define COMPARE_OUTPUT_MODE_TIM0 COMPARE_OUTPUT_MODE_DISCONNECTED
#define GPT_CLK_PRESCALER_TIM0 GPT_CLK_PRESCALER_1024
#endif

#define GPT_TIM1_STATUS 	GPT_OFF

#if GPT_TIM1_STATUS == GPT_ON
#define GPT_TIM1_WAVEFORM_MODE	 GPT_WAVEFORM_MODE_CTC
#define COMPARE_OUTPUT_MODE_TIM1 COMPARE_OUTPUT_MODE_DISCONNECTED
#define GPT_CLK_PRESCALER_TIM1 GPT_CLK_PRESCALER_64
#endif

#define GPT_TIM2_STATUS 	GPT_OFF

#if GPT_TIM2_STATUS == GPT_ON
#define GPT_TIM2_WAVEFORM_MODE	 GPT_WAVEFORM_MODE_CTC
#define COMPARE_OUTPUT_MODE_TIM2 COMPARE_OUTPUT_MODE_DISCONNECTED
#define GPT_CLK_PRESCALER_TIM2 GPT_CLK_PRESCALER_64
#endif

typedef enum {
	GPT_TNT_SOURCE_TIM0_OV,
	GPT_TNT_SOURCE_TIM0_COMPARE,
	GPT_TNT_SOURCE_TIM1_OV,
	GPT_TNT_SOURCE_TIM1A_COMPARE,
	GPT_TNT_SOURCE_TIM1B_COMPARE,
	GPT_TNT_SOURCE_TIM2_OV,
	GPT_TNT_SOURCE_TIM2_COMPARE
} GPT_InterruptSourceType;



void GPT_Init();
void GPT_EnableNotification(GPT_InterruptSourceType Channel);
void GPT_DisableNotification(GPT_InterruptSourceType Channel);

#endif /* GPT_H_ */
